
export const files = [
"2-horas-depois.mp3",
"aaaaaaaaaaeeeeeeitaaaaa.mp3",
"ABERTURA GRATIS . ABERTURA FESTA DJ. RADIOS. WEBRADIOS PROGRAMAS. LINK PARA BAIXAR NA DESCRIÇAO.mp3",
"abertura-poraoke1.mp3",
"abertura-roda-roda-jequiti.mp3",
"acabou-acabou-e-tetra-e-teeetraaa.mp3",
"ah va a merda.mp3",
"Aham-Claudia-Senta-La.mp3",
"alo_5.mp3",
"angustia.mp3",
"velho pai sexta feira.mp3",
"audio-power.mp3",
"BAMBU TA GEMENDO.mp3",
"bilu_01.mp3",
"boa-noite_5RDcvzM.mp3",
"boa-tarde-boa-noite.mp3",
"bom dia xuxuzinho.mp3",
"bom-dia-galera-ha.mp3",
"bom-dia-minha-querida-oia-teria-condies-de-tu-fazer-minha-online-audio-converter.mp3",
"breakinnews.mp3",
"caralho-o-maluco-e-bravo.mp3",
"ce-e-o-bichao-memo-hein-doido-red.mp3",
"chegamos-na-quinta-feira.mp3",
"chupa que a cana é doce.mp3",
"comemoracao_de_sexta_feira.mp3",
"como_voce_ta_diferente_virou_roqueiro_audiosparazap.com.mp3",
"crente_nervoso_no_transito_audiosparazap.com.mp3",
"crimeemcurso.mp3",
"dale-c-quem-eu-falo-original.mp3",
"danca-gatinho-danca.mp3",
"DATENA BABACA.mp3",
"DATENA REALIDADE.mp3",
"detenha-a-contagem.mp3",
"distribuicao-columbia-tristar-international-meme.mp3",
"dramatic.swf.mp3",
"drauzio-vai-tomar-agua.mp3",
"DROGADO NOIA.mp3",
"esse-e-meu-patrao_uo8CCdn.mp3",
"esse-e-o-boldo-bom.mp3",
"EU NÃO SUPORTO MAIS.mp3",
"falar besteira.mp3",
"FATALITY.mp3",
"faustao-errou.mp3",
"finish-him.mp3",
"FUNK RENAN.mp3",
"GALVÃO BUENO NINGUÉM SABE.mp3",
"hadouken.mp3",
"haja-coracao.mp3",
"hitorias-botao.mp3",
"Hoje é  dia do gole, se prejudique.mp3",
"hora-do-shooow-porra.mp3",
"i-love-you_1.mp3",
"iha.mp3",
"JAGUARA.mp3",
"jefinho-cansei-ja.mp3",
"JIRIPOCA VAI PIAR.mp3",
"MAIS.mp3",
"maquina-de-vencer.mp3",
"meajuda.mp3",
"mentira.mp3",
"modem.mp3",
"myvideo_1-online-audio-converter_uDZdojX.mp3",
"nao_ta_chorando_nao_tia_audiosparazap.com.mp3",
"NEGATIVO-COMUNISTINHAD-DE-MERDA.mp3",
"noossa.mp3",
"NOSSA PALMAS PRA ELE.mp3",
"nossa-que-forca-incontrolavel.mp3",
"O QUE É QUE DIZ O LIVRINHO.mp3",
"o_que_nao_acredito_audiosparazap.com.mp3",
"o-brasil-ta-lascado.mp3",
"o-pequeno-urso-abertura-1.mp3",
"OLHA O QUE ELE FEZ.mp3",
"palhaco-triste.mp3",
"PARA COM ESSA PORRA AI MEU IRMÃO.mp3",
"pare.mp3",
"PASSEIO.mp3",
"pastilha-temer.mp3",
"PELOAMORDEDEUS.mp3",
"piao-da-delicia-propria.mp3",
"pica-pau-hm-bolo-de-murango.mp3",
"pichuruco-igor-guimaraes.mp3",
"PLANTAO_GLOBO_-_Trilha_Sonora_Versao_-_Trap_Remix_from17.276353s_to40.564075s.mp3",
"POLICIA MALUCO.mp3",
"PORQUE SERÁ.mp3",
"ptt-20150301-wa0022.mp3",
"quando-eu-te-dou-bom-dia.mp3",
"ratinho_1.mp3",
"risada_carlos_alberto_mp3cut.mp3",
"risada_WqmA1cc.mp3",
"risada-do-bola-marcos-chiesa-mp3cut.mp3",
"risada-ladrao.mp3",
"ritmo de festa.mp3",
"SAI DA FRENTE SATANÁS.mp3",
"seja-bem-vindo-radio-arautos-do-rei.mp3",
"senior.mp3",
"sexta_no_globo_reporter_audiosparazap.com.mp3",
"Sexta-Feira - Áudio lendário do WhatsApp.mp3",
"silvio-santos-o-seu-tempo-acabou.mp3",
"soy-programador-fp-mp3cut.mp3",
"TÁ TÃO ENGRAÇADO.mp3",
"TAVA-FORA-DO-BRASIL-IRMÃO.mp3",
"teclado-lindinho-2009-a.mp3",
"tem_alguem_vivo_ai_audiosparazap.com.mp3",
"TO FICANDO NERVOSO.mp3",
"toguro-motivacional.mp3",
"TORCEDOR DO AMERICA ESSE CARA AINDA TA AI.mp3",
"TOURO CHIFRUDO.mp3",
"trafico-de-farinha-linhares-e-sua-turma.mp3",
"untitled-2_2.mp3",
"vai-fazer-trocadilho-no-inferno-renato-senna-1.mp3",
"vei que viaje é essa vei.mp3",
"Vinheta _Brasil Sil Sil_ - Globo (Anos 2000).mp3",
"vinheta_contagem_regressiva_de_abertura.mp3",
"vinheta-xaropinho-rapaz_dx3f4Be.mp3",
"VIROU PASSEIO.mp3",
"virou-passeio-gol-da-alemanha.mp3",
"vixi-ratinho.mp3",
"welcome to the internet.mp3",

]